#
# Module manifest for module 'Microsoft.Graph.Applications'
#
# Generated by: Microsoft Corporation
#
# Generated on: 12/20/2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = './Microsoft.Graph.Applications.psm1'

# Version number of this module.
ModuleVersion = '2.34.0'

# Supported PSEditions
CompatiblePSEditions = 'Core', 'Desktop'

# ID used to uniquely identify this module
GUID = '467f54f2-44a8-4993-8e75-b96c3e443098'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = 'Microsoft Corporation. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Microsoft Graph PowerShell Cmdlets'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.7.2'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(@{ModuleName = 'Microsoft.Graph.Authentication'; RequiredVersion = '2.34.0'; })

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = './bin/Microsoft.Graph.Applications.private.dll'

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = './Microsoft.Graph.Applications.format.ps1xml'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Add-MgApplicationKey', 'Add-MgApplicationPassword', 
               'Add-MgServicePrincipalKey', 'Add-MgServicePrincipalPassword', 
               'Add-MgServicePrincipalTokenSigningCertificate', 
               'Clear-MgApplicationVerifiedPublisher', 
               'Confirm-MgApplicationMemberGroup', 
               'Confirm-MgApplicationMemberObject', 
               'Confirm-MgServicePrincipalMemberGroup', 
               'Confirm-MgServicePrincipalMemberObject', 
               'Find-MgApplicationSynchronizationJobSchemaDirectory', 
               'Find-MgApplicationSynchronizationTemplateSchemaDirectory', 
               'Find-MgServicePrincipalSynchronizationJobSchemaDirectory', 
               'Find-MgServicePrincipalSynchronizationTemplateSchemaDirectory', 
               'Get-MgApplication', 'Get-MgApplicationAppManagementPolicy', 
               'Get-MgApplicationAppManagementPolicyByRef', 
               'Get-MgApplicationAppManagementPolicyCount', 
               'Get-MgApplicationByAppId', 'Get-MgApplicationById', 
               'Get-MgApplicationByUniqueName', 'Get-MgApplicationCount', 
               'Get-MgApplicationCreatedOnBehalfOf', 'Get-MgApplicationDelta', 
               'Get-MgApplicationExtensionProperty', 
               'Get-MgApplicationExtensionPropertyCount', 
               'Get-MgApplicationFederatedIdentityCredential', 
               'Get-MgApplicationFederatedIdentityCredentialByName', 
               'Get-MgApplicationFederatedIdentityCredentialCount', 
               'Get-MgApplicationHomeRealmDiscoveryPolicy', 
               'Get-MgApplicationHomeRealmDiscoveryPolicyCount', 
               'Get-MgApplicationLogo', 'Get-MgApplicationMemberGroup', 
               'Get-MgApplicationMemberObject', 'Get-MgApplicationOwner', 
               'Get-MgApplicationOwnerAsAppRoleAssignment', 
               'Get-MgApplicationOwnerAsEndpoint', 
               'Get-MgApplicationOwnerAsServicePrincipal', 
               'Get-MgApplicationOwnerAsUser', 'Get-MgApplicationOwnerByRef', 
               'Get-MgApplicationOwnerCount', 
               'Get-MgApplicationOwnerCountAsAppRoleAssignment', 
               'Get-MgApplicationOwnerCountAsEndpoint', 
               'Get-MgApplicationOwnerCountAsServicePrincipal', 
               'Get-MgApplicationOwnerCountAsUser', 
               'Get-MgApplicationSynchronization', 
               'Get-MgApplicationSynchronizationAccessToken', 
               'Get-MgApplicationSynchronizationJob', 
               'Get-MgApplicationSynchronizationJobBulkUpload', 
               'Get-MgApplicationSynchronizationJobBulkUploadContent', 
               'Get-MgApplicationSynchronizationJobCount', 
               'Get-MgApplicationSynchronizationJobSchema', 
               'Get-MgApplicationSynchronizationJobSchemaDirectory', 
               'Get-MgApplicationSynchronizationJobSchemaDirectoryCount', 
               'Get-MgApplicationSynchronizationSecretCount', 
               'Get-MgApplicationSynchronizationTemplate', 
               'Get-MgApplicationSynchronizationTemplateCount', 
               'Get-MgApplicationSynchronizationTemplateSchema', 
               'Get-MgApplicationSynchronizationTemplateSchemaDirectory', 
               'Get-MgApplicationSynchronizationTemplateSchemaDirectoryCount', 
               'Get-MgApplicationTemplate', 'Get-MgApplicationTemplateCount', 
               'Get-MgApplicationTokenIssuancePolicy', 
               'Get-MgApplicationTokenIssuancePolicyByRef', 
               'Get-MgApplicationTokenIssuancePolicyCount', 
               'Get-MgApplicationTokenLifetimePolicy', 
               'Get-MgApplicationTokenLifetimePolicyByRef', 
               'Get-MgApplicationTokenLifetimePolicyCount', 
               'Get-MgGroupAppRoleAssignment', 'Get-MgGroupAppRoleAssignmentCount', 
               'Get-MgServicePrincipal', 
               'Get-MgServicePrincipalAppManagementPolicy', 
               'Get-MgServicePrincipalAppManagementPolicyCount', 
               'Get-MgServicePrincipalAppRoleAssignedTo', 
               'Get-MgServicePrincipalAppRoleAssignedToCount', 
               'Get-MgServicePrincipalAppRoleAssignment', 
               'Get-MgServicePrincipalAppRoleAssignmentCount', 
               'Get-MgServicePrincipalByAppId', 'Get-MgServicePrincipalById', 
               'Get-MgServicePrincipalClaimMappingPolicy', 
               'Get-MgServicePrincipalClaimMappingPolicyByRef', 
               'Get-MgServicePrincipalClaimMappingPolicyCount', 
               'Get-MgServicePrincipalCount', 
               'Get-MgServicePrincipalCreatedObject', 
               'Get-MgServicePrincipalCreatedObjectAsServicePrincipal', 
               'Get-MgServicePrincipalCreatedObjectCount', 
               'Get-MgServicePrincipalCreatedObjectCountAsServicePrincipal', 
               'Get-MgServicePrincipalDelegatedPermissionClassification', 
               'Get-MgServicePrincipalDelegatedPermissionClassificationCount', 
               'Get-MgServicePrincipalDelta', 'Get-MgServicePrincipalEndpoint', 
               'Get-MgServicePrincipalEndpointCount', 
               'Get-MgServicePrincipalHomeRealmDiscoveryPolicy', 
               'Get-MgServicePrincipalHomeRealmDiscoveryPolicyByRef', 
               'Get-MgServicePrincipalHomeRealmDiscoveryPolicyCount', 
               'Get-MgServicePrincipalMemberGroup', 
               'Get-MgServicePrincipalMemberObject', 
               'Get-MgServicePrincipalMemberOf', 
               'Get-MgServicePrincipalMemberOfAsAdministrativeUnit', 
               'Get-MgServicePrincipalMemberOfAsDirectoryRole', 
               'Get-MgServicePrincipalMemberOfAsGroup', 
               'Get-MgServicePrincipalMemberOfCount', 
               'Get-MgServicePrincipalMemberOfCountAsAdministrativeUnit', 
               'Get-MgServicePrincipalMemberOfCountAsDirectoryRole', 
               'Get-MgServicePrincipalMemberOfCountAsGroup', 
               'Get-MgServicePrincipalOauth2PermissionGrant', 
               'Get-MgServicePrincipalOauth2PermissionGrantCount', 
               'Get-MgServicePrincipalOwnedObject', 
               'Get-MgServicePrincipalOwnedObjectAsApplication', 
               'Get-MgServicePrincipalOwnedObjectAsAppRoleAssignment', 
               'Get-MgServicePrincipalOwnedObjectAsEndpoint', 
               'Get-MgServicePrincipalOwnedObjectAsGroup', 
               'Get-MgServicePrincipalOwnedObjectAsServicePrincipal', 
               'Get-MgServicePrincipalOwnedObjectCount', 
               'Get-MgServicePrincipalOwnedObjectCountAsApplication', 
               'Get-MgServicePrincipalOwnedObjectCountAsAppRoleAssignment', 
               'Get-MgServicePrincipalOwnedObjectCountAsEndpoint', 
               'Get-MgServicePrincipalOwnedObjectCountAsGroup', 
               'Get-MgServicePrincipalOwnedObjectCountAsServicePrincipal', 
               'Get-MgServicePrincipalOwner', 
               'Get-MgServicePrincipalOwnerAsAppRoleAssignment', 
               'Get-MgServicePrincipalOwnerAsEndpoint', 
               'Get-MgServicePrincipalOwnerAsServicePrincipal', 
               'Get-MgServicePrincipalOwnerAsUser', 
               'Get-MgServicePrincipalOwnerByRef', 
               'Get-MgServicePrincipalOwnerCount', 
               'Get-MgServicePrincipalOwnerCountAsAppRoleAssignment', 
               'Get-MgServicePrincipalOwnerCountAsEndpoint', 
               'Get-MgServicePrincipalOwnerCountAsServicePrincipal', 
               'Get-MgServicePrincipalOwnerCountAsUser', 
               'Get-MgServicePrincipalRemoteDesktopSecurityConfiguration', 
               'Get-MgServicePrincipalRemoteDesktopSecurityConfigurationTargetDeviceGroup', 
               'Get-MgServicePrincipalRemoteDesktopSecurityConfigurationTargetDeviceGroupCount', 
               'Get-MgServicePrincipalSynchronization', 
               'Get-MgServicePrincipalSynchronizationAccessToken', 
               'Get-MgServicePrincipalSynchronizationJob', 
               'Get-MgServicePrincipalSynchronizationJobBulkUpload', 
               'Get-MgServicePrincipalSynchronizationJobBulkUploadContent', 
               'Get-MgServicePrincipalSynchronizationJobCount', 
               'Get-MgServicePrincipalSynchronizationJobSchema', 
               'Get-MgServicePrincipalSynchronizationJobSchemaDirectory', 
               'Get-MgServicePrincipalSynchronizationJobSchemaDirectoryCount', 
               'Get-MgServicePrincipalSynchronizationSecretCount', 
               'Get-MgServicePrincipalSynchronizationTemplate', 
               'Get-MgServicePrincipalSynchronizationTemplateCount', 
               'Get-MgServicePrincipalSynchronizationTemplateSchema', 
               'Get-MgServicePrincipalSynchronizationTemplateSchemaDirectory', 
               'Get-MgServicePrincipalSynchronizationTemplateSchemaDirectoryCount', 
               'Get-MgServicePrincipalTokenIssuancePolicy', 
               'Get-MgServicePrincipalTokenIssuancePolicyByRef', 
               'Get-MgServicePrincipalTokenIssuancePolicyCount', 
               'Get-MgServicePrincipalTokenLifetimePolicy', 
               'Get-MgServicePrincipalTokenLifetimePolicyByRef', 
               'Get-MgServicePrincipalTokenLifetimePolicyCount', 
               'Get-MgServicePrincipalTransitiveMemberOf', 
               'Get-MgServicePrincipalTransitiveMemberOfAsAdministrativeUnit', 
               'Get-MgServicePrincipalTransitiveMemberOfAsDirectoryRole', 
               'Get-MgServicePrincipalTransitiveMemberOfAsGroup', 
               'Get-MgServicePrincipalTransitiveMemberOfCount', 
               'Get-MgServicePrincipalTransitiveMemberOfCountAsAdministrativeUnit', 
               'Get-MgServicePrincipalTransitiveMemberOfCountAsDirectoryRole', 
               'Get-MgServicePrincipalTransitiveMemberOfCountAsGroup', 
               'Get-MgUserAppRoleAssignment', 'Get-MgUserAppRoleAssignmentCount', 
               'Invoke-MgFilterApplicationSynchronizationJobSchemaOperator', 
               'Invoke-MgFilterApplicationSynchronizationTemplateSchemaOperator', 
               'Invoke-MgFilterServicePrincipalSynchronizationJobSchemaOperator', 
               'Invoke-MgFilterServicePrincipalSynchronizationTemplateSchemaOperator', 
               'Invoke-MgFunctionApplicationSynchronizationJobSchema', 
               'Invoke-MgFunctionApplicationSynchronizationTemplateSchema', 
               'Invoke-MgFunctionServicePrincipalSynchronizationJobSchema', 
               'Invoke-MgFunctionServicePrincipalSynchronizationTemplateSchema', 
               'Invoke-MgInstantiateApplicationTemplate', 
               'Invoke-MgParseApplicationSynchronizationJobSchemaExpression', 
               'Invoke-MgParseApplicationSynchronizationTemplateSchemaExpression', 
               'Invoke-MgParseServicePrincipalSynchronizationJobSchemaExpression', 
               'Invoke-MgParseServicePrincipalSynchronizationTemplateSchemaExpression', 
               'New-MgApplication', 'New-MgApplicationAppManagementPolicyByRef', 
               'New-MgApplicationExtensionProperty', 
               'New-MgApplicationFederatedIdentityCredential', 
               'New-MgApplicationOwnerByRef', 
               'New-MgApplicationSynchronizationJob', 
               'New-MgApplicationSynchronizationJobOnDemand', 
               'New-MgApplicationSynchronizationJobSchemaDirectory', 
               'New-MgApplicationSynchronizationTemplate', 
               'New-MgApplicationSynchronizationTemplateSchemaDirectory', 
               'New-MgApplicationTokenIssuancePolicyByRef', 
               'New-MgApplicationTokenLifetimePolicyByRef', 
               'New-MgGroupAppRoleAssignment', 'New-MgServicePrincipal', 
               'New-MgServicePrincipalAppRoleAssignedTo', 
               'New-MgServicePrincipalAppRoleAssignment', 
               'New-MgServicePrincipalClaimMappingPolicyByRef', 
               'New-MgServicePrincipalDelegatedPermissionClassification', 
               'New-MgServicePrincipalEndpoint', 
               'New-MgServicePrincipalHomeRealmDiscoveryPolicyByRef', 
               'New-MgServicePrincipalOwnerByRef', 
               'New-MgServicePrincipalRemoteDesktopSecurityConfigurationTargetDeviceGroup', 
               'New-MgServicePrincipalSynchronizationJob', 
               'New-MgServicePrincipalSynchronizationJobOnDemand', 
               'New-MgServicePrincipalSynchronizationJobSchemaDirectory', 
               'New-MgServicePrincipalSynchronizationTemplate', 
               'New-MgServicePrincipalSynchronizationTemplateSchemaDirectory', 
               'New-MgServicePrincipalTokenIssuancePolicyByRef', 
               'New-MgServicePrincipalTokenLifetimePolicyByRef', 
               'New-MgUserAppRoleAssignment', 'Remove-MgApplication', 
               'Remove-MgApplicationAppManagementPolicyAppManagementPolicyByRef', 
               'Remove-MgApplicationByAppId', 'Remove-MgApplicationByUniqueName', 
               'Remove-MgApplicationExtensionProperty', 
               'Remove-MgApplicationFederatedIdentityCredential', 
               'Remove-MgApplicationFederatedIdentityCredentialByName', 
               'Remove-MgApplicationKey', 'Remove-MgApplicationLogo', 
               'Remove-MgApplicationOwnerDirectoryObjectByRef', 
               'Remove-MgApplicationPassword', 
               'Remove-MgApplicationSynchronization', 
               'Remove-MgApplicationSynchronizationJob', 
               'Remove-MgApplicationSynchronizationJobBulkUpload', 
               'Remove-MgApplicationSynchronizationJobBulkUploadContent', 
               'Remove-MgApplicationSynchronizationJobSchema', 
               'Remove-MgApplicationSynchronizationJobSchemaDirectory', 
               'Remove-MgApplicationSynchronizationTemplate', 
               'Remove-MgApplicationSynchronizationTemplateSchema', 
               'Remove-MgApplicationSynchronizationTemplateSchemaDirectory', 
               'Remove-MgApplicationTokenIssuancePolicyTokenIssuancePolicyByRef', 
               'Remove-MgApplicationTokenLifetimePolicyTokenLifetimePolicyByRef', 
               'Remove-MgGroupAppRoleAssignment', 'Remove-MgServicePrincipal', 
               'Remove-MgServicePrincipalAppRoleAssignedTo', 
               'Remove-MgServicePrincipalAppRoleAssignment', 
               'Remove-MgServicePrincipalByAppId', 
               'Remove-MgServicePrincipalClaimMappingPolicyClaimMappingPolicyByRef', 
               'Remove-MgServicePrincipalDelegatedPermissionClassification', 
               'Remove-MgServicePrincipalEndpoint', 
               'Remove-MgServicePrincipalHomeRealmDiscoveryPolicyHomeRealmDiscoveryPolicyByRef', 
               'Remove-MgServicePrincipalKey', 
               'Remove-MgServicePrincipalOwnerDirectoryObjectByRef', 
               'Remove-MgServicePrincipalPassword', 
               'Remove-MgServicePrincipalRemoteDesktopSecurityConfiguration', 
               'Remove-MgServicePrincipalRemoteDesktopSecurityConfigurationTargetDeviceGroup', 
               'Remove-MgServicePrincipalSynchronization', 
               'Remove-MgServicePrincipalSynchronizationJob', 
               'Remove-MgServicePrincipalSynchronizationJobBulkUpload', 
               'Remove-MgServicePrincipalSynchronizationJobBulkUploadContent', 
               'Remove-MgServicePrincipalSynchronizationJobSchema', 
               'Remove-MgServicePrincipalSynchronizationJobSchemaDirectory', 
               'Remove-MgServicePrincipalSynchronizationTemplate', 
               'Remove-MgServicePrincipalSynchronizationTemplateSchema', 
               'Remove-MgServicePrincipalSynchronizationTemplateSchemaDirectory', 
               'Remove-MgServicePrincipalTokenIssuancePolicyByRef', 
               'Remove-MgServicePrincipalTokenIssuancePolicyTokenIssuancePolicyByRef', 
               'Remove-MgServicePrincipalTokenLifetimePolicyByRef', 
               'Remove-MgServicePrincipalTokenLifetimePolicyTokenLifetimePolicyByRef', 
               'Remove-MgUserAppRoleAssignment', 
               'Restart-MgApplicationSynchronizationJob', 
               'Restart-MgServicePrincipalSynchronizationJob', 
               'Set-MgApplicationLogo', 'Set-MgApplicationSynchronization', 
               'Set-MgApplicationSynchronizationJobBulkUploadContent', 
               'Set-MgApplicationSynchronizationSecret', 
               'Set-MgApplicationVerifiedPublisher', 
               'Set-MgServicePrincipalSynchronization', 
               'Set-MgServicePrincipalSynchronizationJobBulkUploadContent', 
               'Set-MgServicePrincipalSynchronizationSecret', 
               'Start-MgApplicationSynchronizationJob', 
               'Start-MgServicePrincipalSynchronizationJob', 
               'Suspend-MgApplicationSynchronizationJob', 
               'Suspend-MgServicePrincipalSynchronizationJob', 
               'Test-MgApplicationProperty', 
               'Test-MgApplicationSynchronizationJobCredential', 
               'Test-MgServicePrincipalProperty', 
               'Test-MgServicePrincipalSynchronizationJobCredential', 
               'Update-MgApplication', 'Update-MgApplicationByAppId', 
               'Update-MgApplicationByUniqueName', 
               'Update-MgApplicationExtensionProperty', 
               'Update-MgApplicationFederatedIdentityCredential', 
               'Update-MgApplicationFederatedIdentityCredentialByName', 
               'Update-MgApplicationSynchronizationJob', 
               'Update-MgApplicationSynchronizationJobBulkUpload', 
               'Update-MgApplicationSynchronizationJobSchema', 
               'Update-MgApplicationSynchronizationJobSchemaDirectory', 
               'Update-MgApplicationSynchronizationTemplate', 
               'Update-MgApplicationSynchronizationTemplateSchema', 
               'Update-MgApplicationSynchronizationTemplateSchemaDirectory', 
               'Update-MgGroupAppRoleAssignment', 'Update-MgServicePrincipal', 
               'Update-MgServicePrincipalAppRoleAssignedTo', 
               'Update-MgServicePrincipalAppRoleAssignment', 
               'Update-MgServicePrincipalByAppId', 
               'Update-MgServicePrincipalDelegatedPermissionClassification', 
               'Update-MgServicePrincipalEndpoint', 
               'Update-MgServicePrincipalRemoteDesktopSecurityConfiguration', 
               'Update-MgServicePrincipalRemoteDesktopSecurityConfigurationTargetDeviceGroup', 
               'Update-MgServicePrincipalSynchronizationJob', 
               'Update-MgServicePrincipalSynchronizationJobBulkUpload', 
               'Update-MgServicePrincipalSynchronizationJobSchema', 
               'Update-MgServicePrincipalSynchronizationJobSchemaDirectory', 
               'Update-MgServicePrincipalSynchronizationTemplate', 
               'Update-MgServicePrincipalSynchronizationTemplateSchema', 
               'Update-MgServicePrincipalSynchronizationTemplateSchemaDirectory', 
               'Update-MgUserAppRoleAssignment'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = 'Remove-MgApplicationAppManagementPolicyByRef', 
               'Remove-MgApplicationOwnerByRef', 
               'Remove-MgApplicationTokenIssuancePolicyByRef', 
               'Remove-MgApplicationTokenLifetimePolicyByRef', 
               'Remove-MgServicePrincipalClaimMappingPolicyByRef', 
               'Remove-MgServicePrincipalHomeRealmDiscoveryPolicyByRef', 
               'Remove-MgServicePrincipalOwnerByRef'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Microsoft','Office365','Graph','PowerShell','PSModule','PSIncludes_Cmdlet'

        # A URL to the license for this module.
        LicenseUri = 'https://aka.ms/devservicesagreement'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/microsoftgraph/msgraph-sdk-powershell'

        # A URL to an icon representing this module.
        IconUri = 'https://raw.githubusercontent.com/microsoftgraph/msgraph-sdk-powershell/dev/docs/images/graph_color256.png'

        # ReleaseNotes of this module
        ReleaseNotes = 'See https://aka.ms/GraphPowerShell-Release.'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}


# SIG # Begin signature block
# MIIoKgYJKoZIhvcNAQcCoIIoGzCCKBcCAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCD+9kMmLZ3R/Ac7
# XrZWPe6n8vvVLZywCef6VrUjooWIrKCCDXYwggX0MIID3KADAgECAhMzAAAEhV6Z
# 7A5ZL83XAAAAAASFMA0GCSqGSIb3DQEBCwUAMH4xCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNpZ25p
# bmcgUENBIDIwMTEwHhcNMjUwNjE5MTgyMTM3WhcNMjYwNjE3MTgyMTM3WjB0MQsw
# CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
# ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMR4wHAYDVQQDExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
# AQDASkh1cpvuUqfbqxele7LCSHEamVNBfFE4uY1FkGsAdUF/vnjpE1dnAD9vMOqy
# 5ZO49ILhP4jiP/P2Pn9ao+5TDtKmcQ+pZdzbG7t43yRXJC3nXvTGQroodPi9USQi
# 9rI+0gwuXRKBII7L+k3kMkKLmFrsWUjzgXVCLYa6ZH7BCALAcJWZTwWPoiT4HpqQ
# hJcYLB7pfetAVCeBEVZD8itKQ6QA5/LQR+9X6dlSj4Vxta4JnpxvgSrkjXCz+tlJ
# 67ABZ551lw23RWU1uyfgCfEFhBfiyPR2WSjskPl9ap6qrf8fNQ1sGYun2p4JdXxe
# UAKf1hVa/3TQXjvPTiRXCnJPAgMBAAGjggFzMIIBbzAfBgNVHSUEGDAWBgorBgEE
# AYI3TAgBBggrBgEFBQcDAzAdBgNVHQ4EFgQUuCZyGiCuLYE0aU7j5TFqY05kko0w
# RQYDVR0RBD4wPKQ6MDgxHjAcBgNVBAsTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEW
# MBQGA1UEBRMNMjMwMDEyKzUwNTM1OTAfBgNVHSMEGDAWgBRIbmTlUAXTgqoXNzci
# tW2oynUClTBUBgNVHR8ETTBLMEmgR6BFhkNodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
# b20vcGtpb3BzL2NybC9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3JsMGEG
# CCsGAQUFBwEBBFUwUzBRBggrBgEFBQcwAoZFaHR0cDovL3d3dy5taWNyb3NvZnQu
# Y29tL3BraW9wcy9jZXJ0cy9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3J0
# MAwGA1UdEwEB/wQCMAAwDQYJKoZIhvcNAQELBQADggIBACjmqAp2Ci4sTHZci+qk
# tEAKsFk5HNVGKyWR2rFGXsd7cggZ04H5U4SV0fAL6fOE9dLvt4I7HBHLhpGdE5Uj
# Ly4NxLTG2bDAkeAVmxmd2uKWVGKym1aarDxXfv3GCN4mRX+Pn4c+py3S/6Kkt5eS
# DAIIsrzKw3Kh2SW1hCwXX/k1v4b+NH1Fjl+i/xPJspXCFuZB4aC5FLT5fgbRKqns
# WeAdn8DsrYQhT3QXLt6Nv3/dMzv7G/Cdpbdcoul8FYl+t3dmXM+SIClC3l2ae0wO
# lNrQ42yQEycuPU5OoqLT85jsZ7+4CaScfFINlO7l7Y7r/xauqHbSPQ1r3oIC+e71
# 5s2G3ClZa3y99aYx2lnXYe1srcrIx8NAXTViiypXVn9ZGmEkfNcfDiqGQwkml5z9
# nm3pWiBZ69adaBBbAFEjyJG4y0a76bel/4sDCVvaZzLM3TFbxVO9BQrjZRtbJZbk
# C3XArpLqZSfx53SuYdddxPX8pvcqFuEu8wcUeD05t9xNbJ4TtdAECJlEi0vvBxlm
# M5tzFXy2qZeqPMXHSQYqPgZ9jvScZ6NwznFD0+33kbzyhOSz/WuGbAu4cHZG8gKn
# lQVT4uA2Diex9DMs2WHiokNknYlLoUeWXW1QrJLpqO82TLyKTbBM/oZHAdIc0kzo
# STro9b3+vjn2809D0+SOOCVZMIIHejCCBWKgAwIBAgIKYQ6Q0gAAAAAAAzANBgkq
# hkiG9w0BAQsFADCBiDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24x
# EDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
# bjEyMDAGA1UEAxMpTWljcm9zb2Z0IFJvb3QgQ2VydGlmaWNhdGUgQXV0aG9yaXR5
# IDIwMTEwHhcNMTEwNzA4MjA1OTA5WhcNMjYwNzA4MjEwOTA5WjB+MQswCQYDVQQG
# EwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwG
# A1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQg
# Q29kZSBTaWduaW5nIFBDQSAyMDExMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIIC
# CgKCAgEAq/D6chAcLq3YbqqCEE00uvK2WCGfQhsqa+laUKq4BjgaBEm6f8MMHt03
# a8YS2AvwOMKZBrDIOdUBFDFC04kNeWSHfpRgJGyvnkmc6Whe0t+bU7IKLMOv2akr
# rnoJr9eWWcpgGgXpZnboMlImEi/nqwhQz7NEt13YxC4Ddato88tt8zpcoRb0Rrrg
# OGSsbmQ1eKagYw8t00CT+OPeBw3VXHmlSSnnDb6gE3e+lD3v++MrWhAfTVYoonpy
# 4BI6t0le2O3tQ5GD2Xuye4Yb2T6xjF3oiU+EGvKhL1nkkDstrjNYxbc+/jLTswM9
# sbKvkjh+0p2ALPVOVpEhNSXDOW5kf1O6nA+tGSOEy/S6A4aN91/w0FK/jJSHvMAh
# dCVfGCi2zCcoOCWYOUo2z3yxkq4cI6epZuxhH2rhKEmdX4jiJV3TIUs+UsS1Vz8k
# A/DRelsv1SPjcF0PUUZ3s/gA4bysAoJf28AVs70b1FVL5zmhD+kjSbwYuER8ReTB
# w3J64HLnJN+/RpnF78IcV9uDjexNSTCnq47f7Fufr/zdsGbiwZeBe+3W7UvnSSmn
# Eyimp31ngOaKYnhfsi+E11ecXL93KCjx7W3DKI8sj0A3T8HhhUSJxAlMxdSlQy90
# lfdu+HggWCwTXWCVmj5PM4TasIgX3p5O9JawvEagbJjS4NaIjAsCAwEAAaOCAe0w
# ggHpMBAGCSsGAQQBgjcVAQQDAgEAMB0GA1UdDgQWBBRIbmTlUAXTgqoXNzcitW2o
# ynUClTAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTALBgNVHQ8EBAMCAYYwDwYD
# VR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBRyLToCMZBDuRQFTuHqp8cx0SOJNDBa
# BgNVHR8EUzBRME+gTaBLhklodHRwOi8vY3JsLm1pY3Jvc29mdC5jb20vcGtpL2Ny
# bC9wcm9kdWN0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3JsMF4GCCsG
# AQUFBwEBBFIwUDBOBggrBgEFBQcwAoZCaHR0cDovL3d3dy5taWNyb3NvZnQuY29t
# L3BraS9jZXJ0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3J0MIGfBgNV
# HSAEgZcwgZQwgZEGCSsGAQQBgjcuAzCBgzA/BggrBgEFBQcCARYzaHR0cDovL3d3
# dy5taWNyb3NvZnQuY29tL3BraW9wcy9kb2NzL3ByaW1hcnljcHMuaHRtMEAGCCsG
# AQUFBwICMDQeMiAdAEwAZQBnAGEAbABfAHAAbwBsAGkAYwB5AF8AcwB0AGEAdABl
# AG0AZQBuAHQALiAdMA0GCSqGSIb3DQEBCwUAA4ICAQBn8oalmOBUeRou09h0ZyKb
# C5YR4WOSmUKWfdJ5DJDBZV8uLD74w3LRbYP+vj/oCso7v0epo/Np22O/IjWll11l
# hJB9i0ZQVdgMknzSGksc8zxCi1LQsP1r4z4HLimb5j0bpdS1HXeUOeLpZMlEPXh6
# I/MTfaaQdION9MsmAkYqwooQu6SpBQyb7Wj6aC6VoCo/KmtYSWMfCWluWpiW5IP0
# wI/zRive/DvQvTXvbiWu5a8n7dDd8w6vmSiXmE0OPQvyCInWH8MyGOLwxS3OW560
# STkKxgrCxq2u5bLZ2xWIUUVYODJxJxp/sfQn+N4sOiBpmLJZiWhub6e3dMNABQam
# ASooPoI/E01mC8CzTfXhj38cbxV9Rad25UAqZaPDXVJihsMdYzaXht/a8/jyFqGa
# J+HNpZfQ7l1jQeNbB5yHPgZ3BtEGsXUfFL5hYbXw3MYbBL7fQccOKO7eZS/sl/ah
# XJbYANahRr1Z85elCUtIEJmAH9AAKcWxm6U/RXceNcbSoqKfenoi+kiVH6v7RyOA
# 9Z74v2u3S5fi63V4GuzqN5l5GEv/1rMjaHXmr/r8i+sLgOppO6/8MO0ETI7f33Vt
# Y5E90Z1WTk+/gFcioXgRMiF670EKsT/7qMykXcGhiJtXcVZOSEXAQsmbdlsKgEhr
# /Xmfwb1tbWrJUnMTDXpQzTGCGgowghoGAgEBMIGVMH4xCzAJBgNVBAYTAlVTMRMw
# EQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVN
# aWNyb3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNp
# Z25pbmcgUENBIDIwMTECEzMAAASFXpnsDlkvzdcAAAAABIUwDQYJYIZIAWUDBAIB
# BQCgga4wGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQwHAYKKwYBBAGCNwIBCzEO
# MAwGCisGAQQBgjcCARUwLwYJKoZIhvcNAQkEMSIEIDJpJh5znfhPe58WBaLWAXPo
# q3akN+y29jRkQ71UhOtCMEIGCisGAQQBgjcCAQwxNDAyoBSAEgBNAGkAYwByAG8A
# cwBvAGYAdKEagBhodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20wDQYJKoZIhvcNAQEB
# BQAEggEANcXDxXq43FvGXo31g6CajgwXqLd0lRrmADFkB6hihTucIGyT0q6Ioedb
# vkAQKg4Zh88zcaautZFINzzMUqQedbr/+T12LuQJdc9iLUl4NvgazOEJ8cTT1Grv
# mw/G74JzawaV8kEX51M+VQTr8TYiNlcrE7fceaaL5M840D0FkYc9JL4ghtJrsS4J
# 2zP+BmFIopd729U/z6QGb/RQC6F5FFlUBBwVDlv/QX63IB2UdBGB+Sx5aA9zm8tr
# RShE96LLn795RGIoDu4lIkOuz2sxoEAbHbFtO26Zz9JZ+V4KxzBMtUIZ2mTlHORb
# MEzHuHCyU+YwWkEGi83tcalYDWVveaGCF5QwgheQBgorBgEEAYI3AwMBMYIXgDCC
# F3wGCSqGSIb3DQEHAqCCF20wghdpAgEDMQ8wDQYJYIZIAWUDBAIBBQAwggFSBgsq
# hkiG9w0BCRABBKCCAUEEggE9MIIBOQIBAQYKKwYBBAGEWQoDATAxMA0GCWCGSAFl
# AwQCAQUABCCtaP1ntJDVVLkUg9YQbqF11VAPy5bx7my06pvvkoMSjAIGaUSC6VYi
# GBMyMDI1MTIyMDA3NDI1Mi45NDJaMASAAgH0oIHRpIHOMIHLMQswCQYDVQQGEwJV
# UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UE
# ChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSUwIwYDVQQLExxNaWNyb3NvZnQgQW1l
# cmljYSBPcGVyYXRpb25zMScwJQYDVQQLEx5uU2hpZWxkIFRTUyBFU046N0YwMC0w
# NUUwLUQ5NDcxJTAjBgNVBAMTHE1pY3Jvc29mdCBUaW1lLVN0YW1wIFNlcnZpY2Wg
# ghHqMIIHIDCCBQigAwIBAgITMwAAAgbXvFE4mCPsLAABAAACBjANBgkqhkiG9w0B
# AQsFADB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UE
# BxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYD
# VQQDEx1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMDAeFw0yNTAxMzAxOTQy
# NTBaFw0yNjA0MjIxOTQyNTBaMIHLMQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2Fz
# aGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENv
# cnBvcmF0aW9uMSUwIwYDVQQLExxNaWNyb3NvZnQgQW1lcmljYSBPcGVyYXRpb25z
# MScwJQYDVQQLEx5uU2hpZWxkIFRTUyBFU046N0YwMC0wNUUwLUQ5NDcxJTAjBgNV
# BAMTHE1pY3Jvc29mdCBUaW1lLVN0YW1wIFNlcnZpY2UwggIiMA0GCSqGSIb3DQEB
# AQUAA4ICDwAwggIKAoICAQDpRIWbIM3Rlr397cjHaYx85l7I+ZVWGMCBCM911BpU
# 6+IGWCqksqgqefZFEjKzNVDYC9YcgITAz276NGgvECm4ZfNv/FPwcaSDz7xbDbsO
# oxbwQoHUNRro+x5ubZhT6WJeU97F06+vDjAw/Yt1vWOgRTqmP/dNr9oqIbE5oCLY
# dH3wI/noYmsJVc7966n+B7UAGAWU2se3Lz+xdxnNsNX4CR6zIMVJTSezP/2STNcx
# JTu9k2sl7/vzOhxJhCQ38rdaEoqhGHrXrmVkEhSv+S00DMJc1OIXxqfbwPjMqEVp
# 7K3kmczCkbum1BOIJ2wuDAbKuJelpteNZj/S58NSQw6khfuJAluqHK3igkS/Oux4
# 9qTP+rU+PQeNuD+GtrCopFucRmanQvxISGNoxnBq3UeDTqphm6aI7GMHtFD6DOjJ
# lllH1gVWXPTyivf+4tN8TmO6yIgB4uP00bH9jn/dyyxSjxPQ2nGvZtgtqnvq3h3T
# RjRnkc+e1XB1uatDa1zUcS7r3iodTpyATe2hgkVX3m4DhRzI6A4SJ6fbJM9isLH8
# AGKcymisKzYupAeFSTJ10JEFa6MjHQYYohoCF77R0CCwMNjvE4XfLHu+qKPY8GQf
# sZdigQ9clUAiydFmVt61hytoxZP7LmXbzjD0VecyzZoL4Equ1XszBsulAr5Ld2Kw
# cwIDAQABo4IBSTCCAUUwHQYDVR0OBBYEFO0wsLKdDGpT97cx3Iymyo/SBm4SMB8G
# A1UdIwQYMBaAFJ+nFV0AXmJdg/Tl0mWnG1M1GelyMF8GA1UdHwRYMFYwVKBSoFCG
# Tmh0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvY3JsL01pY3Jvc29mdCUy
# MFRpbWUtU3RhbXAlMjBQQ0ElMjAyMDEwKDEpLmNybDBsBggrBgEFBQcBAQRgMF4w
# XAYIKwYBBQUHMAKGUGh0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvY2Vy
# dHMvTWljcm9zb2Z0JTIwVGltZS1TdGFtcCUyMFBDQSUyMDIwMTAoMSkuY3J0MAwG
# A1UdEwEB/wQCMAAwFgYDVR0lAQH/BAwwCgYIKwYBBQUHAwgwDgYDVR0PAQH/BAQD
# AgeAMA0GCSqGSIb3DQEBCwUAA4ICAQB23GZOfe9ThTUvD29i4t6lDpxJhpVRMme+
# UbyZhBFCZhoGTtjDdphAArU2Q61WYg3YVcl2RdJm5PUbZ2bA77zk+qtLxC+3dNxV
# sTcdtxPDSSWgwBHxTj6pCmoDNXolAYsWpvHQFCHDqEfAiBxX1dmaXbiTP1d0Xffv
# gR6dshUcqaH/mFfjDZAxLU1s6HcVgCvBQJlJ7xEG5jFKdtqapKWcbUHwTVqXQGbI
# lHVClNJ3yqW6Z3UJH/CFcYiLV/e68urTmGtiZxGSYb4SBSPArTrTYeHOlQIj/7lo
# VWmfWX2y4AGV/D+MzyZMyvFw4VyL0Vgq96EzQKyteiVeBaVEjxQKo3AcPULRF4Uz
# z98P2tCM5XbFZ3Qoj9PLg3rgFXr0oJEhfh2tqUrhTJd13+i4/fek9zWicoshlwXg
# Fu002ZWBVzASEFuqED48qyulZ/2jGJBcta+Fdk2loP2K3oSj4PQQe1MzzVZO52AX
# O42MHlhm3SHo3/RhQ+I1A0Ny+9uAehkQH6LrxkrVNvZG4f0PAKMbqUcXG7xznKJ0
# x0HYr5ayWGbHKZRcObU+/34ZpL9NrXOedVDXmSd2ylKSl/vvi1QwNJqXJl/+gJkQ
# EetqmHAUFQkFtemi8MUXQG2w/RDHXXwWAjE+qIDZLQ/k4z2Z216tWaR6RDKHGkwe
# CoDtQtzkHTCCB3EwggVZoAMCAQICEzMAAAAVxedrngKbSZkAAAAAABUwDQYJKoZI
# hvcNAQELBQAwgYgxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAw
# DgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24x
# MjAwBgNVBAMTKU1pY3Jvc29mdCBSb290IENlcnRpZmljYXRlIEF1dGhvcml0eSAy
# MDEwMB4XDTIxMDkzMDE4MjIyNVoXDTMwMDkzMDE4MzIyNVowfDELMAkGA1UEBhMC
# VVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNV
# BAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRp
# bWUtU3RhbXAgUENBIDIwMTAwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoIC
# AQDk4aZM57RyIQt5osvXJHm9DtWC0/3unAcH0qlsTnXIyjVX9gF/bErg4r25Phdg
# M/9cT8dm95VTcVrifkpa/rg2Z4VGIwy1jRPPdzLAEBjoYH1qUoNEt6aORmsHFPPF
# dvWGUNzBRMhxXFExN6AKOG6N7dcP2CZTfDlhAnrEqv1yaa8dq6z2Nr41JmTamDu6
# GnszrYBbfowQHJ1S/rboYiXcag/PXfT+jlPP1uyFVk3v3byNpOORj7I5LFGc6XBp
# Dco2LXCOMcg1KL3jtIckw+DJj361VI/c+gVVmG1oO5pGve2krnopN6zL64NF50Zu
# yjLVwIYwXE8s4mKyzbnijYjklqwBSru+cakXW2dg3viSkR4dPf0gz3N9QZpGdc3E
# XzTdEonW/aUgfX782Z5F37ZyL9t9X4C626p+Nuw2TPYrbqgSUei/BQOj0XOmTTd0
# lBw0gg/wEPK3Rxjtp+iZfD9M269ewvPV2HM9Q07BMzlMjgK8QmguEOqEUUbi0b1q
# GFphAXPKZ6Je1yh2AuIzGHLXpyDwwvoSCtdjbwzJNmSLW6CmgyFdXzB0kZSU2LlQ
# +QuJYfM2BjUYhEfb3BvR/bLUHMVr9lxSUV0S2yW6r1AFemzFER1y7435UsSFF5PA
# PBXbGjfHCBUYP3irRbb1Hode2o+eFnJpxq57t7c+auIurQIDAQABo4IB3TCCAdkw
# EgYJKwYBBAGCNxUBBAUCAwEAATAjBgkrBgEEAYI3FQIEFgQUKqdS/mTEmr6CkTxG
# NSnPEP8vBO4wHQYDVR0OBBYEFJ+nFV0AXmJdg/Tl0mWnG1M1GelyMFwGA1UdIARV
# MFMwUQYMKwYBBAGCN0yDfQEBMEEwPwYIKwYBBQUHAgEWM2h0dHA6Ly93d3cubWlj
# cm9zb2Z0LmNvbS9wa2lvcHMvRG9jcy9SZXBvc2l0b3J5Lmh0bTATBgNVHSUEDDAK
# BggrBgEFBQcDCDAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTALBgNVHQ8EBAMC
# AYYwDwYDVR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBTV9lbLj+iiXGJo0T2UkFvX
# zpoYxDBWBgNVHR8ETzBNMEugSaBHhkVodHRwOi8vY3JsLm1pY3Jvc29mdC5jb20v
# cGtpL2NybC9wcm9kdWN0cy9NaWNSb29DZXJBdXRfMjAxMC0wNi0yMy5jcmwwWgYI
# KwYBBQUHAQEETjBMMEoGCCsGAQUFBzAChj5odHRwOi8vd3d3Lm1pY3Jvc29mdC5j
# b20vcGtpL2NlcnRzL01pY1Jvb0NlckF1dF8yMDEwLTA2LTIzLmNydDANBgkqhkiG
# 9w0BAQsFAAOCAgEAnVV9/Cqt4SwfZwExJFvhnnJL/Klv6lwUtj5OR2R4sQaTlz0x
# M7U518JxNj/aZGx80HU5bbsPMeTCj/ts0aGUGCLu6WZnOlNN3Zi6th542DYunKmC
# VgADsAW+iehp4LoJ7nvfam++Kctu2D9IdQHZGN5tggz1bSNU5HhTdSRXud2f8449
# xvNo32X2pFaq95W2KFUn0CS9QKC/GbYSEhFdPSfgQJY4rPf5KYnDvBewVIVCs/wM
# nosZiefwC2qBwoEZQhlSdYo2wh3DYXMuLGt7bj8sCXgU6ZGyqVvfSaN0DLzskYDS
# PeZKPmY7T7uG+jIa2Zb0j/aRAfbOxnT99kxybxCrdTDFNLB62FD+CljdQDzHVG2d
# Y3RILLFORy3BFARxv2T5JL5zbcqOCb2zAVdJVGTZc9d/HltEAY5aGZFrDZ+kKNxn
# GSgkujhLmm77IVRrakURR6nxt67I6IleT53S0Ex2tVdUCbFpAUR+fKFhbHP+Crvs
# QWY9af3LwUFJfn6Tvsv4O+S3Fb+0zj6lMVGEvL8CwYKiexcdFYmNcP7ntdAoGokL
# jzbaukz5m/8K6TT4JDVnK+ANuOaMmdbhIurwJ0I9JZTmdHRbatGePu1+oDEzfbzL
# 6Xu/OHBE0ZDxyKs6ijoIYn/ZcGNTTY3ugm2lBRDBcQZqELQdVTNYs6FwZvKhggNN
# MIICNQIBATCB+aGB0aSBzjCByzELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hp
# bmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jw
# b3JhdGlvbjElMCMGA1UECxMcTWljcm9zb2Z0IEFtZXJpY2EgT3BlcmF0aW9uczEn
# MCUGA1UECxMeblNoaWVsZCBUU1MgRVNOOjdGMDAtMDVFMC1EOTQ3MSUwIwYDVQQD
# ExxNaWNyb3NvZnQgVGltZS1TdGFtcCBTZXJ2aWNloiMKAQEwBwYFKw4DAhoDFQAE
# a0f118XHM/VNdqKBs4QXxNnN96CBgzCBgKR+MHwxCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1w
# IFBDQSAyMDEwMA0GCSqGSIb3DQEBCwUAAgUA7PBSvzAiGA8yMDI1MTIxOTIyMzk1
# OVoYDzIwMjUxMjIwMjIzOTU5WjB0MDoGCisGAQQBhFkKBAExLDAqMAoCBQDs8FK/
# AgEAMAcCAQACAiI3MAcCAQACAhX4MAoCBQDs8aQ/AgEAMDYGCisGAQQBhFkKBAIx
# KDAmMAwGCisGAQQBhFkKAwKgCjAIAgEAAgMHoSChCjAIAgEAAgMBhqAwDQYJKoZI
# hvcNAQELBQADggEBAG5MV0nFiCnYSCzio/KYdiXWRXK+Rv4YBISYgQ9CRvFIdwoB
# vs1dNXijUZQU7w9OJbhahiIRNV/Dg6C7fa4Rg5pwibKQSwyCZpqv77Z7RIPNtG0G
# AyD9I5fJnWYXMYvwvRX41Mva/sEKp75Q+ihfgnKpYWTxAZTRR52wNUpbsseuKcuy
# jIK8qHMiN7wTBZF2pJq/pxv9TsvKnVAa38I5L6aDZ+J9NeRRBXf8jIftjz3aPlij
# IYw6ddXM342SgiLIPAc2zzBfI97XZJWMtTYEsIkhV7SBQXDY+9WL8c2sEskw47gi
# 90wGXs2ekoM3lF31jFI8Dy7HFMOs+Vp68ysYhZIxggQNMIIECQIBATCBkzB8MQsw
# CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
# ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQDEx1NaWNy
# b3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMAITMwAAAgbXvFE4mCPsLAABAAACBjAN
# BglghkgBZQMEAgEFAKCCAUowGgYJKoZIhvcNAQkDMQ0GCyqGSIb3DQEJEAEEMC8G
# CSqGSIb3DQEJBDEiBCCtrUsF9k0e2pQ5Ubta5NCK66+4IEWYWe+aum2EUWHibzCB
# +gYLKoZIhvcNAQkQAi8xgeowgecwgeQwgb0EIODo9ZSIkZ6dVtKT+E/uZx2WAy7K
# iXM5R1JIOhNJf0vSMIGYMIGApH4wfDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldh
# c2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBD
# b3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIw
# MTACEzMAAAIG17xROJgj7CwAAQAAAgYwIgQgD7vmY7L3PoPxgfJ+Ih9n9w4z/WIW
# 9a7K3xp5wdv2Cm4wDQYJKoZIhvcNAQELBQAEggIADxZyWSfno2s79WRHiAhw0kqa
# F/C37RkynZw8j2X73df23pr46jNbMqcOSRDNne1bbUPw63UywOoLrUm8UTHvrU1i
# zmHv/LbbaQo7NRYP1JIV+CnyoNZfH8PXggpPhJip8FwoQc5sNL17sbAmmUG3gEpS
# zf/pOvp33AYiD0KFS2O2aiKtYannYACqWRJgJaH3KzXWpLTmwOoYgfXS9923Nj3k
# 8SDGieIonJAYRNnMpsj0WCjSxBJeOlFAlQ72pqX+waGDJJn9pwEZK1OBCNOQDwx8
# qMYrFPoxH3uhh0ko4AwMz0puuMd98TERXDJYgiqF4t6LHy6MZvBcniBukt+EBFu2
# bgqx3YomKanBcze1o06pwsKJXUKeT+m4BpXhsJAkIfQ5/7/v/1wCdkXqhB670ueF
# LmLejtOs8nKclMJSIaqBbRZdaGpRsJBC5iso4poehZAqRKRcCxkKkxHD7CLvPerI
# GD59XVq/e1eZedq3S2i0er5XYdb6dJ4736t9mFWjwslem6AqpltOyV7rE+DlLzCs
# BW3D1L4Geo/Gq3MxlvEplQd97HdYiPNe9WamGw2o5exWlVQogVjojBp0x3ccKRTR
# oq2b/7R9CSXRc1fenUfDrnKGnIzfPPQKsWtm6hmCvLOEOt3vsZU9Da/+DJJ5kS/F
# xlghhozYms25ixZ5tEA=
# SIG # End signature block
